version: "3.8"

services:
  front-api-service:
    container_name: front-api-container
    build:
      context: .
      dockerfile: frontApi.Dockerfile
    image: front-api-service
    environment:
      - ASPNETCORE_URLS=http://bk-container:3000
      - Eureka__Client__ServiceUrl=http://serviceDiscovery:8761/eureka/
      - Eureka__Client__ShouldRegisterWithEureka=true
      - Eureka__Client__ValidateCertificates=false
    restart: always
    networks:
      - gateway_network
    ports:
      - "8000:8000"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${Sa_Password:-password123}
      - MSSQL_PID=Developer
    command: /bin/bash ./entrypoint.sh
    ports:
      - 1433:1433
    volumes:
      - sqlserver_data:/var/opt/mssql
      - ./Tools/Db/entrypoint.sh:/entrypoint.sh
      - ./Tools/Db/db-init.sh:/db-init.sh
      - ./Tools/Db/db-init.sql:/db-init.sql
    restart: always
    depends_on:
      - sqlserver.configurator
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${Sa_Password:-Passw0rd} -Q 'SELECT 1' || exit 1",
        ]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 20s
      retries: 5
    networks:
      - gateway_network
  redis:
    image: redis:7
    restart: always
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - gateway_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30
  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    environment:
      - node.name=es-node
      - cluster.name=es-cluster
      - discovery.type=single-node
    networks:
      - gateway_network
    volumes:
      - local_es:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9200"]
      interval: 10s
      timeout: 10s
      retries: 5

volumes:
  sqlserver_data:
    driver: local
  local_es:
    driver: local
  front_api_data:
    driver: local

networks:
  gateway_network:
    driver: bridge
