version: "3.3"

services:
  backend-api-service:
    container_name: backend-api-container
    build:
      context: .
      dockerfile: ./backend.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMqSettings:Host=rabbitmq
      - ElasticApm:ServerUrls=http://elasticsearch:9200
      - ElasticsearchSettings:Uri=http://elasticsearch:9200
      - ConnectionStrings:DbConnection="Server=db;User Id=postgres;Password=postgres;Database=postgres;MultipleActiveResultSets=true;TrustServerCertificate=True"
    extends:
      file: docker-compose.base.yml
      service: backend-api-service
    restart: unless-stopped
    command: ["dotnet", "ef", "database update"]
    ports:
      - "3000:3000"
    volumes:
      - backend-api-service:/usr/src/app/backend-api-service

  backend-worker-service:
    container_name: backend-worker-service
    build:
      context: .
      dockerfile: ./backend.worker.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMqSettings:Host=rabbitmq
      - ElasticApm:ServerUrls=http://elasticsearch:9200
      - ElasticsearchSettings:Uri=http://elasticsearch:9200
      - ConnectionStrings:DbConnection="Server=db;User Id=postgres;Password=postgres;Database=postgres;MultipleActiveResultSets=true;TrustServerCertificate=True"
    extends:
      file: docker-compose.base.yml
      service: backend-worker-service
    restart: unless-stopped
    command: ["dotnet", "ef", "database update"]
    ports:
      - "3000:3000"
    volumes:
      - backend-worker-service:/usr/src/app/backend-worker-service
volumes:
  db_data:
    driver: local
  local_es:
    driver: local
  redis_data:
    driver: local
  backend-worker-service:
    driver: local
  backend-api-service:
    driver: local

networks:
  gateway_network:
    driver: bridge
