version: "3.3"

services:
  front-api-service:
    container_name: front-api-container
    build:
      context: .
      dockerfile: ./frontApi.Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMqSettings:Host=rabbitmq
      - ElasticApm:ServerUrls=http://elasticsearch:9200
      - ElasticsearchSettings:Uri=http://elasticsearch:9200
      - ConnectionStrings:DbConnection="Server=db;Database=platform;User Id=developer;Password=developer123!;MultipleActiveResultSets=true;TrustServerCertificate=True"
    extends:
      file: docker-compose.base.yml
      service: front-api-service
    restart: unless-stopped
    command: ["dotnet", "ef", "database update"]
    ports:
      - "3000:3000"
    volumes:
      - front-api-service:/usr/src/app/front_api_service

volumes:
  db_data:
    driver: local
  local_es:
    driver: local
  redis_data:
    driver: local
  front-api-service:
    driver: local

networks:
  gateway_network:
    driver: bridge
