version: "3.3"

services:
  front-api-service:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DbConnection=Server=localhost;Port=${DB_PORT};Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
    extends:
      file: docker-compose.base.yml
      service: front-api-service
    restart: always
    volumes:
      - front-api-service:/usr/src/app/front_api_service
    depends_on:
      - db
      - redis
      - rabbitmq
      - elasticsearch
  db:
    extends:
      file: docker-compose.base.yml
      service: db
  rabbitmq:
    extends:
      file: docker-compose.base.yml
      service: rabbitmq
  redis:
    extends:
      file: docker-compose.base.yml
      service: redis
    volumes:
      - redis_data:/var/lib/redis:/data
  elasticsearch:
    extends:
      file: docker-compose.base.yml
      service: elasticsearch

volumes:
  pgdata:
    driver: local
  redis_data:
    driver: local
  front-api-service:
    driver: local

networks:
  rabbitmq_net:
    driver: bridge
