# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Main CI

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  pull_request:
    branches: [ main ]
  workflow_dispatch:
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  projects-test-CI:
    runs-on: ubuntu-latest
    name: Projects Test Runner
    strategy:
      matrix:
        projectPaths:
          - "Domain.Persistence.Test"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
          dotnet-quality: "preview"
      # service tests
      - name: Run Tests
        run: |
          for path in ${{ join( matrix.projectPaths , ' ')}} }}; do
            echo "Tests Start for $path"
            cd ${{ github.workspace }}/backend/$path && dotnet restore
            cd ${{ github.workspace }}/backend/$path && dotnet build --no-restore
            cd ${{ github.workspace }}/backend/$path && dotnet test --no-build --verbosity normal
            echo "Tests Finished for $path"
          done
  backend-api-service:
    runs-on: ubuntu-latest
    name: Front Api Validation & Build
    needs: [ projects-test-CI ]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8
          dotnet-quality: "preview"
      # build and compile
      - name: Restore dependencies
        run: cd ${{ github.workspace }}/backend/Services/Backend && dotnet restore
      - name: Build
        run: cd ${{ github.workspace }}/backend/Services/Backend && dotnet build --no-restore
  frontend-platforms:
    name: Frontend Platforms & Build
    runs-on: macos-latest
    permissions:
      contents: "read"
      actions: "read"
    strategy:
      matrix:
        projectPaths:
          - "clientFront"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Build And Test Frontend Clients
        run: |
          for path in ${{ join( matrix.projectPaths , ' ')}} }}; do
            echo "Tests Start for $path"
            cd ${{ github.workspace }}/frontend/$path && flutter pub get
            cd ${{ github.workspace }}/frontend/$path && flutter test
            cd ${{ github.workspace }}/frontend/$path && flutter build apk
            cd ${{ github.workspace }}/frontend/$path && flutter build ios --release --no-codesign
            cd ${{ github.workspace }}/frontend/$path && flutter build web
            echo "Tests Finished for $path"
          done
